### ISSUE TITLE
Actions and states return nan

### ISSUE THREAD

**Issue by KevinDu1** [danijar/dreamerv3#26] opened 2023-03-07 10:10 UTC
This is really a great job. Thanks for sharing this amazing work.

When I run the training script

`python` dreamerv3/train.py   --logdir ~/logdir/$(date "+%Y%m%d-%H%M%S")   --configs crafter small --batch_size 16 --run.train_ratio 32 `

The code runs stably at the beginning and reports an error after training for a while,  
`Exception: Traceback (most recent call last):
  File "/home/kevin/dreamerv3-latest/dreamerv3/embodied/core/worker.py", line 202, in _loop
    state, result = function(state, *args, **kwargs)
  File "/home/kevin/dreamerv3-latest/dreamerv3/embodied/core/parallel.py", line 40, in _respond
    result = getattr(state, name)(*args, **kwargs)
  File "/home/kevin/dreamerv3-latest/dreamerv3/embodied/core/wrappers.py", line 158, in step
    obs = self.env.step(action)
  File "/home/kevin/dreamerv3-latest/dreamerv3/embodied/core/wrappers.py", line 113, in step
    assert action[self._key].min() == 0.0, action
AssertionError: {'action': array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan], dtype=float32), 'reset': False}`

Please tell me, how to avoid it, and how to modify the code

**Comment by danijar** [comment] 2023-03-07 22:55
Do you know if this happens with all of your training runs eventually or just rarely? Is there anything specific about your environment that might be relevant? This could be caused by Adam converging and be avoided by setting `--model_opt.eps 1e-5`.

**Comment by KevinDu1** [comment] 2023-03-08 03:26
Thanks you for your quick answer. I both use the original parameters in configs.yaml and the configuration you provided `--model_opt.eps 1e-5` to conduct experiments, and both experiments returned action=array {nan}. Specifically, in one of the experiments, in step 54 (steps=100), the algorithm debugging error occurred at line 42 of driver.py, the code is shown below, and the parameter `self` contains`self._acts={'action'=[nan],'log_entropy'=[nan],'reset'=False},self_state={0=[nan]}`, 

```
  def __call__(self, policy, steps=0, episodes=0):
    step, episode = 0, 0
    while step < steps or episode < episodes:
      step, episode = self._step(policy, step, episode)

```

**Comment by signalprime** [comment] 2023-04-13 19:42
I'm actually investigating the same phenomenon occurring in driver.py _during evaluation_ when using `embodied.run.train_eval(agent, env, eval_env, replay, eval_replay, logger, args)`.  I'll report back if I find out why.  I was implementing a basic optimization problem with an observation space of rank 2.. sometimes it wanted to refer to the vector as 'image/obs', other times 'vector' (since that was how I labeled it in the dictionary), other times 'vector/vector'.  I had not run into that before.  I played around with `mlp_keys` by using "vector", "*"vector*", "vector.*", etc and finally settled on '$^' and making several patches in the code which probably resulted in the error during the evaluation cycle.

`config = config.update({
    'logdir': './logdir/',
    'run.eval_every':1500,
    'run.train_ratio': 64,
    'run.log_every': 30,
    'batch_size': 16,
    'jax.prealloc': False,
    'encoder.mlp_keys': '$^',
    'decoder.mlp_keys': '$^',
    'encoder.cnn_keys': '$^', 
    'decoder.cnn_keys': '$^',
    'replay_size': 1e5,
})
env = from_gym.FromGym(gym_env, obs_key='vector')
`

**Comment by danijar** [comment] 2023-04-14 18:58
Please keep me posted and let me know if I can help, would definitely be good to figure out what's happening here. Just a quick pointer, the `obs*` probably doesn't do what you want because as a regex, it matches `ob`, `obs`, `obssss`, etc.

**Comment by danijar** [comment] 2023-04-15 17:07
Hi all, I've encountered some NaNs also when training `dmc_dog_walk` with mixed precision. With `--jax.precision float32` it works fine though. Could you please try whether that fixes the issue in your cases, too?

**Comment by danijar** [comment] 2024-04-19 22:55
Occasional NaNs are fixed now in the updated paper and code by using an improved optimizer.

For dog, the issue was that the foot contact sensors can return very large observation values that exceed the fp16 range. Dreamer handles this fine using symlog, but symlog needs to be applied in fp32 before casting down to fp16 for the neural network.

**Closed by danijar** 2024-04-19 22:55 UTC
